%import common.WS
%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER -> NUMBER
%ignore WS

STRING : /[a-zA-Z_][a-zA-Z0-9_']*/

all : (line "\n")* line 
line : definition
     | declaration
     | expression
     

definition : variable_defn
           | function_defn
           
variable_defn : new_variable "=" expression
function_defn : new_variable new_variable "=" expression

new_variable : STRING

expression : value         | "(" value ")"
           | variable      | "(" variable ")"
           | function_call | "(" function_call ")"
           | infix_call    | "(" infix_call ")"
           | chain         | "(" chain ")"
           | lambda        | "(" lambda ")"

value : ESCAPED_STRING 
      | NUMBER

variable : STRING

function_call : function function_arg ["$"]
function : expression
function_arg : expression 

infix_call : expression "`" infix "`" expression
infix : variable

declaration : new_variable "::" type
type : atom_type
     | function_type

function_type : "{" type "->" type "}"
atom_type : variable 

chain : "{" expression ( "->" expression )+ "}"

lambda : "fun" variable "=>" expression