version: 2.1

jobs:

  # using tox
  toxify:
      docker:
        - image: python:3.9
      steps:
        - checkout
        - run: pip install tox && tox

  codecov:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run: pip install codecov && codecov

workflows:
  myproj:
    jobs:
      - toxify
      - codecov
