version: 2.1

jobs:

  # using tox
  toxify:

      docker:
        - image: python:3.9

      steps:

        - checkout

        - run: pip install tox && tox

workflows:
  myproj:
    jobs:
      - toxify
